// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using webapi.Models;

namespace webapi.Models
{
    public partial class DEMOContext
    {
        private IDEMOContextProcedures _procedures;

        public virtual IDEMOContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DEMOContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IDEMOContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetMonthlySummaryResult>().HasNoKey().ToView(null);
        }
    }

    public partial class DEMOContextProcedures : IDEMOContextProcedures
    {
        private readonly DEMOContext _context;

        public DEMOContextProcedures(DEMOContext context)
        {
            _context = context;
        }

        public virtual async Task<int> AddMonthlySummaryAsync(string ReportDate, string DataYM, string CompanyCode, string CompanyName, string Industry, long? NowRevenue, long? LastMonthRevenue, long? LastYearSameMonthRevenue, double? MonthlyPercent, double? YearlyPercent, long? CumulativeNowRevenue, long? CumulativeLastYearRevenue, double? CumulativeChangePercent, string Comment, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ReportDate",
                    Size = 14,
                    Value = ReportDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DataYM",
                    Size = 12,
                    Value = DataYM ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CompanyCode",
                    Size = 20,
                    Value = CompanyCode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CompanyName",
                    Size = 100,
                    Value = CompanyName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Industry",
                    Size = 100,
                    Value = Industry ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "NowRevenue",
                    Value = NowRevenue ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "LastMonthRevenue",
                    Value = LastMonthRevenue ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "LastYearSameMonthRevenue",
                    Value = LastYearSameMonthRevenue ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "MonthlyPercent",
                    Value = MonthlyPercent ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "YearlyPercent",
                    Value = YearlyPercent ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "CumulativeNowRevenue",
                    Value = CumulativeNowRevenue ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "CumulativeLastYearRevenue",
                    Value = CumulativeLastYearRevenue ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "CumulativeChangePercent",
                    Value = CumulativeChangePercent ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "Comment",
                    Size = -1,
                    Value = Comment ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[AddMonthlySummary] @ReportDate = @ReportDate, @DataYM = @DataYM, @CompanyCode = @CompanyCode, @CompanyName = @CompanyName, @Industry = @Industry, @NowRevenue = @NowRevenue, @LastMonthRevenue = @LastMonthRevenue, @LastYearSameMonthRevenue = @LastYearSameMonthRevenue, @MonthlyPercent = @MonthlyPercent, @YearlyPercent = @YearlyPercent, @CumulativeNowRevenue = @CumulativeNowRevenue, @CumulativeLastYearRevenue = @CumulativeLastYearRevenue, @CumulativeChangePercent = @CumulativeChangePercent, @Comment = @Comment", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<GetMonthlySummaryResult>> GetMonthlySummaryAsync(string CompanyCode, string DataYM, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "CompanyCode",
                    Size = 20,
                    Value = CompanyCode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DataYM",
                    Size = 12,
                    Value = DataYM ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetMonthlySummaryResult>("EXEC @returnValue = [dbo].[GetMonthlySummary] @CompanyCode = @CompanyCode, @DataYM = @DataYM", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
