// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using webapi.Models;

namespace webapi.Models
{
    public partial interface IDEMOContextProcedures
    {
        Task<int> AddMonthlySummaryAsync(string ReportDate, string DataYM, string CompanyCode, string CompanyName, string Industry, long? NowRevenue, long? LastMonthRevenue, long? LastYearSameMonthRevenue, double? MonthlyPercent, double? YearlyPercent, long? CumulativeNowRevenue, long? CumulativeLastYearRevenue, double? CumulativeChangePercent, string Comment, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetMonthlySummaryResult>> GetMonthlySummaryAsync(string CompanyCode, string DataYM, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
