// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models
{
    public partial class MonthlySummary
    {
        [Required]
        [StringLength(7)]
        public string ReportDate { get; set; }
        [Key]
        [StringLength(6)]
        public string DataYM { get; set; }
        [Key]
        [StringLength(10)]
        public string CompanyCode { get; set; }
        [Required]
        [StringLength(50)]
        public string CompanyName { get; set; }
        [Required]
        [StringLength(50)]
        public string Industry { get; set; }
        public long NowRevenue { get; set; }
        public long LastMonthRevenue { get; set; }
        public long LastYearSameMonthRevenue { get; set; }
        public double? MonthlyPercent { get; set; }
        public double? YearlyPercent { get; set; }
        public long CumulativeNowRevenue { get; set; }
        public long CumulativeLastYearRevenue { get; set; }
        public double? CumulativeChangePercent { get; set; }
        public string Comment { get; set; }
    }
}